#!/usr/bin/env python3
"""Deterministic generation and fail-closed repository supervision (stdlib only)."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def tracked_and_new_files():
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=ROOT, check=True, capture_output=True,
    )
    return sorted({Path(p.decode()) for p in result.stdout.split(b"\0") if p
                   if (ROOT / p.decode()).is_file()})


def source_directories():
    result = {Path(".")}
    for path in tracked_and_new_files():
        result.update(path.parents)
    return sorted(result)


def check_locked_files(manifest):
    lock = json.loads((ROOT / manifest).read_text())
    for entry in lock["files"]:
        data = (ROOT / entry["local"]).read_bytes()
        blob = b"blob " + str(len(data)).encode() + b"\0" + data
        if hashlib.sha256(data).hexdigest() != entry["sha256"]:
            raise ValueError(f"Upstream SHA-256 mismatch: {entry['local']}")
        if hashlib.sha1(blob).hexdigest() != entry["git_blob"]:
            raise ValueError(f"Upstream Git blob mismatch: {entry['local']}")
    return lock


def check_upstream():
    return check_locked_files("spec/upstream.lock.json")


def remove_comments(text):
    # HOL source uses nested ML comments. Do not inventory commented definitions.
    out, depth, pos = [], 0, 0
    while pos < len(text):
        if text[pos:pos+2] == "(*":
            if not depth:
                out.append(" ")
            depth += 1
            pos += 2
        elif text[pos:pos+2] == "*)" and depth:
            depth -= 1
            pos += 2
        else:
            if not depth or text[pos] == "\n":
                out.append(text[pos])
            pos += 1
    if depth:
        raise ValueError("Unterminated upstream comment")
    return "".join(out)


def generated_files():
    check_upstream()
    syntax = remove_comments((ROOT / "spec/upstream/holSyntaxScript.sml").read_text())
    datatype = re.search(r"Datatype:\s*type\s*=\s*(.*?)\nEnd", syntax, re.S)
    if not datatype:
        raise ValueError("Missing HOL type datatype")
    variants = []
    for variant in datatype[1].split("|"):
        fields = re.fullmatch(r"\s*(\w+)\s+mlstring\s*(\(type list\))?\s*", variant)
        if not fields:
            raise ValueError("Unsupported HOL datatype shape; audit generator before porting")
        variants.append(f"    {fields[1]}(Vec<u8>{', Vec<HolType>' if fields[2] else ''}),")
    init = remove_comments((ROOT / "spec/upstream/ml_hol_kernel_funsProgScript.sml").read_text())
    definition = re.search(r"Definition init_type_constants_def:\s*init_type_constants = \[(.*?)\]\s*End", init, re.S)
    if not definition:
        raise ValueError("Missing initial type constants")
    entries = []
    for item in definition[1].split(";"):
        entry = re.fullmatch(r"\s*\(«([a-zA-Z_]+)»,(\d+)(?::num)?\)\s*", item)
        if not entry:
            raise ValueError("Unsupported initial constant; audit generator before porting")
        entries.append(f'        (b"{entry[1]}".to_vec(), {entry[2]}),')
    rust = "\n".join([
        "// @generated by tools/repo.py from pinned CakeML HOL definitions.",
        "// Do not edit. Upstream notices: spec/upstream/LICENSE.CakeML.",
        "/// Raw HOL type syntax; construction alone is not a type_ok certificate.",
        "#[derive(Clone, Debug, PartialEq, Eq)]",
        "pub enum HolType {", *variants, "}", "",
        "pub(crate) fn initial_types() -> Vec<(Vec<u8>, usize)> {",
        "    vec![", *entries, "    ]", "}", "",
    ])
    # Use the same pinned formatter as CI, so generation and format checks agree.
    rust = subprocess.run(["rustfmt", "--edition", "2024", "--emit", "stdout"],
                          input=rust, text=True, capture_output=True, check=True).stdout
    kernel = remove_comments((ROOT / "spec/upstream/holKernelScript.sml").read_text())
    definitions = re.findall(r"^Definition\s+(\w+)(?:\[[^\]]*\])?:", kernel, re.M)
    mapping = json.loads((ROOT / "spec/implementation.json").read_text())
    unknown = set(mapping) - set(definitions)
    if unknown:
        raise ValueError(f"Mapped definitions not found upstream: {sorted(unknown)}")
    rows = ["# Kernel definition inventory", "",
            "Generated from the pinned `holKernelScript.sml`; this indexes explicit",
            "definitions, not all generated HOL constants or the entire Candle system.",
            "Implemented means code exists, not that unbounded equivalence is proved.", "",
            "| Upstream definition | Rust implementation | Status |",
            "| --- | --- | --- |"]
    for name in definitions:
        if name in mapping:
            item = mapping[name]
            rows.append(f"| `{name}` | `{item['rust']}` | {item['status']} |")
        else:
            rows.append(f"| `{name}` | — | Not implemented |")
    return {"src/generated.rs": rust, "docs/generated/kernel-inventory.md": "\n".join(rows) + "\n"}


def sync_agents(check=False):
    canonical = (ROOT / "AGENTS.md").read_bytes()
    errors = []
    for directory in source_directories():
        path = ROOT / directory / "AGENTS.md"
        if path.is_symlink():
            raise ValueError(f"Refusing instruction symlink: {path.relative_to(ROOT)}")
        if not path.exists() or path.read_bytes() != canonical:
            if check:
                errors.append(str(path.relative_to(ROOT)))
            else:
                path.write_bytes(canonical)
    if errors:
        raise ValueError("Missing/divergent AGENTS.md: " + ", ".join(errors))


def check_obligations():
    manifest = json.loads((ROOT / "spec/obligations.json").read_text())
    budget = manifest["harness_timeout_seconds"]
    if type(budget) is not int or budget <= 0:
        raise ValueError("Kani harness timeout must be a positive number of seconds")
    if not manifest["bounded_properties"]:
        raise ValueError("Kani harness inventory must not be empty")
    source = (ROOT / "src/proofs.rs").read_text()
    actual = re.findall(r"#\[kani::proof\]\s*#\[kani::unwind\((\d+)\)\]\s*fn (\w+)", source)
    expected = [(str(item["unwind"]), item["harness"]) for item in manifest["bounded_properties"]]
    if len(actual) != len(set(actual)) or sorted(actual) != sorted(expected):
        raise ValueError("Kani harness/manifest mismatch (including bounds)")
    ids = [item["id"] for item in manifest["bounded_properties"]]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate obligation ID")
    if len(re.findall(r"#\[kani::proof\]", source)) != len(actual):
        raise ValueError("Every Kani harness needs an explicit, registered unwind bound")
    for item in manifest["bounded_properties"]:
        if not item["domain"] or not item["upstream"]:
            raise ValueError("Property is missing its domain or upstream definition")


def check():
    check_locked_files("verification/reuse.lock.json")
    expected = generated_files()
    for path, content in expected.items():
        if not (ROOT / path).exists() or (ROOT / path).read_text() != content:
            raise ValueError(f"Generated drift: {path}; run python3 tools/repo.py generate")
    sync_agents(check=True)
    check_obligations()
    for path in tracked_and_new_files():
        if path.name.lower() == "agents.md" and path.name != "AGENTS.md":
            raise ValueError(f"Wrong instruction filename case: {path}")
    print("Upstream digests, generated files, instructions, and proof inventory agree.")


def source_digest():
    digest = hashlib.sha256()
    for path in tracked_and_new_files():
        digest.update(str(path).encode() + b"\0")
        digest.update(hashlib.sha256((ROOT / path).read_bytes()).digest())
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["generate", "sync-agents", "check", "digest"])
    args = parser.parse_args()
    try:
        if args.command == "generate":
            for path, content in generated_files().items():
                (ROOT / path).parent.mkdir(parents=True, exist_ok=True)
                (ROOT / path).write_text(content)
            sync_agents()
        elif args.command == "sync-agents":
            sync_agents()
        elif args.command == "digest":
            print(source_digest())
        else:
            check()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
