// @generated by tools/repo.py from pinned CakeML HOL definitions.
// Do not edit. Upstream notices: spec/upstream/LICENSE.CakeML.
/// Raw HOL type syntax; construction alone is not a type_ok certificate.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum HolType {
    Tyvar(Vec<u8>),
    Tyapp(Vec<u8>, Vec<HolType>),
}

pub(crate) fn initial_types() -> Vec<(Vec<u8>, usize)> {
    vec![(b"bool".to_vec(), 0), (b"fun".to_vec(), 2)]
}
